### ISSUE TITLE
Internal: Authentication Process Migration into the App

### ISSUE THREAD

**Issue by livingmydesign** [livingmydesign/hdstories#24]
**Scope:**
External: Token-Generation via Get-Request
Internal: DB-Requests, SendGrid API-Call

=> Make.com => CloudFunctions/FF-Actions

**Tasks**

- [ ] Validate SendGrid API Functionality in Flutterflow
- [ ] Migration of Auth-Scenarios into Actions on a new Auth-Page in Flutterflow
- [ ] Creation of additional GetToken-Make-Scenario
- [ ] Test-Runs
